import type { Metadata } from "next";
import { Noto_Sans_JP } from "next/font/google";
import { Jost } from "next/font/google";
import "./globals.scss";

const notosans = Noto_Sans_JP({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja" >
      <body className={notosans.className}>
        {children}
        <footer className="bg-color1 min-h-svh sm:min-h-96">


        </footer>
      </body>

    </html>
  );
}
